---
- name: Ensuring apt dependencies are installed
  ansible.builtin.apt:
    pkg:
    - apache2
    - apache2-dev
    - git
    - ufw
    - python3-venv
    - python3-pip

- name: Installing Django
  ansible.builtin.pip:
    name: 
    - Django
    - mod_wsgi
